**Task-1: Write one line of Python code to access and print the value 400**

In [ ]:
a_tuple = ("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717,
[1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
print(a_tuple[3][3])

400


**Task-2:Assume, you have been given a tuple. Write a Python program that creates a new tuple excluding the first and last two elements of the given tuple and prints the new tuple.
Hint: You may use tuple slicing.**

In [ ]:
tpl = tuple(int(item) for item in input('Enter Tuple: ')[1:-1].split(', '))
tpl = tpl[2:-2]
print(tpl)

Enter Tuple: (-10, 20, 25, 30, 40)
(25,)


**Task-3:Assume, you have been given a tuple.
book_info = (
("Best Mystery & Thriller","The Silent Patient",68,821),
("Best Horror","The Institute",75,717),
("Best History & Biography","The five",31,783 ),
("Best Fiction","The Testaments",98,291)
)
Write a Python program that prints the size of the tuple and all its elements as shown below.**

In [ ]:
book_info = (
("Best Mystery & Thriller","The Silent Patient",68, 821),
("Best Horror","The Institute",75, 717),
("Best History & Biography","The five",31, 783 ),
("Best Fiction","The Testaments",98, 291)
)
print(f'Size of the tuple is: {len(book_info)}')
for i in book_info:
  print(i)


4
('Best Mystery & Thriller', 'The Silent Patient', 68821)
('Best Horror', 'The Institute', 75717)
('Best History & Biography', 'The five', 31783)
('Best Fiction', 'The Testaments', 98291)


**Task-4**:Assume, you have been given a tuple with details about books that won the Good Reads Choice Awards.
book_info = (
("Best Mystery & Thriller","The Silent Patient",68821),
("Best Horror","The Institute",75717),
("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291)
) 
Write a Python program that prints the award category, the book name, and its total votes earned as shown below.

Output:
The Silent Patient won the 'Best Mystery & Thriller' category with 68821 votes
The Institute won the 'Best Horror' category with 75717 votes
The five won the 'Best History & Biography' category with 31783 votes
The Testaments won the 'Best Fiction' category with 98291 votes

In [ ]:
book_info = (
("Best Mystery & Thriller","The Silent Patient",68821),
("Best Horror","The Institute",75717),
("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291)
)
for i in book_info:
  a,b,c = i
  print(f"{b} won the \'{a}\' category with {c} votes ")


**Task-5:** Write a python program that takes an input from the user and finds the number of times that the input is present in a given tuple.


In [ ]:
given = (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
n = int(input("Enter any number within the given tuple: "))
count = 0
for i in given:
  if n == i:
    count += 1
print(f"{n} appears {count} times in the tuple ")

Enter any number within the given tuple: 8
8 appears 4 times in the tuple 


**Task-6:** Write a Python program to reverse a given tuple.

In [ ]:
tpl = ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
new = []
for i in range (len(tpl)-1,-1,-1):
  new.append(tpl[i])
new = tuple(new)
print(new)

('h', 'g', 'f', 'e', 'd', 'c', 'b', 'a')


**Task-7:** Now create a new dictionary "marks", merging the two dictionaries, so that the original two dictionaries remain unchanged.

In [ ]:
x = {'Harry':15, 'Draco':8, 'Nevil':19}
y = {'Ginie':18, 'Luna': 14}
marks = x.copy()
marks.update(y)
print(marks)

{'Harry': 15, 'Draco': 8, 'Nevil': 19, 'Ginie': 18, 'Luna': 14}


**Task-8:** Write a Python program that takes a dictionary as an input from the user and then prints the average of all the values in the dictionary.

In [1]:
s = input("Enter a dictionary: ").split(', ')
d = {}
n = []
for i in s:
  i = i.split(':')
  for j in i:
    n.append(j)
n2 = []
for i in range(len(n)):
  if i % 2 != 0:
    n[i] = int(n[i])
    n2.append(n[i])
  else:
    n2.append(n[i])
value = []
for i in range(len(n2)):
  if type(n2[i]) == int:
    value.append(n2[i])
sum = 0
count = 0
for i in value:
  sum += i
  count += 1
avg = sum/count
print(f"Average is {int(avg)}.")
 
#Jon:100, Dan:200, Rob:300


Enter a dictionary: Jon:100, Dan:200, Rob:30, Ned:110
Average is 110.


**Task-9:** Suppose there is a dictionary named exam_marks as given below.
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
Write a Python program that takes an input from the user and creates a new dictionary with only those elements from 'exam_marks' whose keys have values higher than the user input (inclusive).

In [ ]:
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
n = int(input("Enter a mark: "))
dic = {}
for i in exam_marks.keys():
  if exam_marks[i] >= n:
    dic[i] = exam_marks[i]
  else:
    pass
print(dic)

Enter a mark: 170
{'Cierra Vega': 175, 'Alden Cantrell': 200, 'Pierre Cox': 190}


**Task-10:** Write a Python program that finds the largest value with its key from a given dictionary

In [ ]:
# given = {'sci fi': 12, 'mystery': 15, 'horror': 8, 'mythology': 10, 'young_adult': 4, 'adventure':14}
given = {'sci fi': 5, 'mystery': 3, 'horror': 14, 'young_adult': 2, 'adventure':9} #Both given inputs work
value = given.values()
max = 0
for i in value:
  if i >= max:
    max = i
  else:
    pass
for i in given:
  if given[i] == max:
    print(f"The highest selling book genre is '{i}' and the number of books sold are {max}.")

The highest selling book genre is 'horror' and the number of books sold are 14.


**Task-11:** Write a Python program that takes a String as an input from the user and counts the frequency of each character using a dictionary. For solving this problem, you may use each character as a key and its frequency as values. [You are not allowed to use the count() function]

In [ ]:
s = input("Enter a string using quotes: ")[1:-1].lower()
dic = {}
for i in s:
  if i == ' ':
    pass
  elif i in dic.keys():
    dic[i] += 1
  else:
    dic[i] = 1
print(dic)

Enter a string using quotes: "Python programming is fun"
{'p': 2, 'y': 1, 't': 1, 'h': 1, 'o': 2, 'n': 3, 'r': 2, 'g': 2, 'a': 1, 'm': 2, 'i': 2, 's': 1, 'f': 1, 'u': 1}


**Task-12:** Suppose you are given the following dictionary where the values are lists.
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
Write a Python program that counts the total number of items in a dictionary’s values and prints it. 

In [ ]:
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
count = 0
for i in dict_1.values():
  for j in i:
    count += 1
print(count)

9


**Task-13:** Suppose you have been given the following list of tuples.
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
Write a Python program that converts this list of tuples into a dictionary and then prints the dictionary. The items in each tuple are a key and its value respectively. You need to group the values with the same keys into a list as shown below.
[You are not allowed to use set]
Hint: Think of membership operators (in and not in).

In [ ]:
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
dic = {}
for i in list_1:
  k,v = i
  if k in dic:
    dic[k].append(v)
    continue
  dic[k] = [v]
print(dic)

{'a': [1, 3, 2], 'b': [2, 1], 'c': [1]}
